// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase values removed for public repository safety.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: 'FIREBASE_APP_ID_REMOVED',
    messagingSenderId: 'FIREBASE_SENDER_ID_REMOVED',
    projectId: 'FIREBASE_PROJECT_ID_REMOVED',
    authDomain: 'FIREBASE_AUTH_DOMAIN_REMOVED',
    storageBucket: 'FIREBASE_STORAGE_BUCKET_REMOVED',
    measurementId: 'FIREBASE_MEASUREMENT_ID_REMOVED',
  );

  // Firebase values removed for public repository safety.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: 'FIREBASE_APP_ID_REMOVED',
    messagingSenderId: 'FIREBASE_SENDER_ID_REMOVED',
    projectId: 'FIREBASE_PROJECT_ID_REMOVED',
    storageBucket: 'FIREBASE_STORAGE_BUCKET_REMOVED',
  );
}
